# DAY 27

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('D:/REGEX/DAY_27/IMDB Dataset.csv')

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [6]:
df['review']=df['review'].str.lower()

In [7]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

### REMOVE HTML TAGS

In [14]:
import re

def remove_html_tags(text):
    pattern=re.compile('<.*?>')
    return pattern.sub(r' ',text)

In [15]:
text="<html><body><p>Movies1</p><p>Click here to <a href='https://google.com'>download</a></p>"

In [16]:
remove_html_tags(text)

'   Movies1  Click here to  download  '

In [17]:
# now we remove tags from IMDB Datasets
df['review']=df['review'].apply(remove_html_tags)

In [18]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production.   the filming t...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [19]:
df['review'].unique

<bound method Series.unique of 0        one of the other reviewers has mentioned that ...
1        a wonderful little production.   the filming t...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object>

### IF WE WANT TO REMOVE URLS FROM TEXT THEN

In [29]:
def remove_url(text):
    pattern=re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r' ',text)

In [30]:
text4='for notebook click https://www.google.com/skj'

In [31]:
remove_url(text4)

'for notebook click  '

### STEP-4 REMOVE PUNCTUATION

In [32]:
import string 
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [33]:
exclude=string.punctuation

In [35]:
def remove_punctuation(text):
    for char in exclude:
        text=text.replace(char,' ')
    return text

In [36]:
text1="Q3 WHAT IS PUNCTUATION"

In [37]:
remove_punctuation(text1)

'Q3 WHAT IS PUNCTUATION'

In [38]:
df['review']=df['review'].apply(remove_punctuation)

In [39]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production    the filming t...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there s a family where a little boy ...  negative
4  petter mattei s  love in the time of money  is...  positive

### STEP -6 SPELLING CORRECTION

In [ ]:
# pip install TextBlob

In [40]:
from textblob import TextBlob

In [44]:
incorrect_text="cererticical condittion severall generator sahil shankar"

In [48]:
textblob=TextBlob(incorrect_text)
textblob.correct().string

'cererticical condition several generation sail shankar'

In [46]:
textblob

TextBlob("cererticical condittion severall generator sahil shankar")

### STEP - 7 REMOVING STEPWORDS

In [49]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [50]:
STOPWORDS=set(stopwords.words('english'))

#### STOPWORDS

##### MANUALLY WORK

In [57]:
def remove_stopwords(text):
    new_text=[]
    for word in text.split():
        if word in set(stopwords.words('english')):
            new_text.append('')
        else:
            new_text.append(word)

    x=new_text[:]
    new_text.clear()
    return "".join(x)

remove_stopwords('probability my all-time favourite movies, a story of selflessness')

'probabilityall-timefavouritemovies,storyselflessness'

### TOKENIZATION

In [58]:
# 1. PREFFIX - CHARACTER(s) AT THE BEGINING =$(" .)

# 2. SUFFIX - CHARATERS(s) AT THE END = KM).!"

# 3. infix - charater(s)  in the between = --/..

# 4. Expection - special-case rule to split a string into several tokens or prevent a token from being split when punctuation rules are applied ,=let's start

In [61]:
# APPROACH THE TOKENIZATION  USING SPLIT FUNCTION

sent1='I am shankar'
sent1.split()

['I', 'am', 'shankar']

In [ ]:
# Sentence Tockenization
sent2=''

# 1. NLTK

In [63]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [64]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [66]:
sent1="I am going to delhi!"
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'delhi', '!']

In [67]:
sent2='I HAVE A PH.D. in A.I.'
sent3="we 're here to help! mail us at nks@gmail.com"
sent4="A sia ride cost $10.23"

In [68]:
word_tokenize(sent2)

['I', 'HAVE', 'A', 'PH.D.', 'in', 'A.I', '.']

In [69]:
word_tokenize(sent3)

['we',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nks',
 '@',
 'gmail.com']

In [70]:
word_tokenize(sent4)

['A', 'sia', 'ride', 'cost', '$', '10.23']

# TEXT REPRESENTATION

In [171]:
# 1. Bag of words
# we use countvectorization

In [172]:
import numpy as np
import pandas as pd

In [173]:
df=pd.DataFrame({'text':['people watch cricket','player was player','people write comment','cricket play comment'],'output':[1,1,0,0]})

In [174]:
df.head()

                   text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [175]:
df

                   text  output
0  people watch cricket       1
1     player was player       1
2  people write comment       0
3  cricket play comment       0

In [176]:
from sklearn.feature_extraction.text import CountVectorizer

In [177]:
cv=CountVectorizer()

In [178]:
bow=cv.fit_transform(df['text'])

In [179]:
# vocab
print(cv.vocabulary_) # to find unique words

{'people': 2, 'watch': 6, 'cricket': 1, 'player': 4, 'was': 5, 'write': 7, 'comment': 0, 'play': 3}

In [180]:
print(bow[0].toarray())
print(bow[1].toarray())

[[0 1 1 0 0 0 1 0]]
[[0 0 0 0 2 1 0 0]]

In [181]:
cv.transform(["cricket watch and write comment of cricket comment"]).toarray()

array([[2, 2, 0, 0, 0, 0, 1, 1]])

# 2. N-GRAM TECHIQUE

In [182]:
# use when we want cosine simalirity of the text

In [183]:
# cv=CountVectorizer(ngram_range=(2,2))

In [184]:
v=CountVectorizer(ngram_range=(1,2))
# v=CountVectorizer(ngram_range=(2,2))

In [185]:
bow=v.fit_transform(df['text'])

In [188]:
df['text']

0    people watch cricket
1       player was player
2    people write comment
3    cricket play comment
Name: text, dtype: object

In [187]:
# vocab
print(v.vocabulary_)

{'people': 3, 'watch': 12, 'cricket': 1, 'people watch': 4, 'watch cricket': 13, 'player': 8, 'was': 10, 'player was': 9, 'was player': 11, 'write': 14, 'comment': 0, 'people write': 5, 'write comment': 15, 'play': 6, 'cricket play': 2, 'play comment': 7}

In [148]:
# TF(Term Frequencey) 
# 2. IDF(Inverse Document Frequencey)

In [147]:
# TF(t,d) = (Number of occurences of term t in document d)/(Total number of terms in the document d) 
# example ==>
# d1 = people watch cricket . 

# tf(people,d1) = 1/3 

# d2 = match was match. 
# tf(match , d2) = 2/3

In [145]:
# IDF(t) = loge(Total number of documents in the corpus)/(Number of documents with term t in them) 
# here corpus means number of sentences

# Example ==>
# d1 = people watch cricket . 
# d2 = cricket was cricket . 
# d3 = people write comment .
# d4 = cricket write comment . 

# idf(cricket) = log(4/4)
# idf(people) = log(4/2)

In [146]:
# we can use this by apply feature_extraction method in sklearn

In [142]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.52640543, 0.52640543, 0.        , 0.        ,
        0.        , 0.66767854, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.89442719,
        0.4472136 , 0.        , 0.        ],
       [0.52640543, 0.        , 0.52640543, 0.        , 0.        ,
        0.        , 0.        , 0.66767854],
       [0.52640543, 0.52640543, 0.        , 0.66767854, 0.        ,
        0.        , 0.        , 0.        ]])

In [144]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.51082562 1.51082562 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073 1.91629073]
['comment' 'cricket' 'people' 'play' 'player' 'was' 'watch' 'write']